[platformio]
src_dir = .

[env:esp32-sim7600]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200
build_flags = -D TINY_GSM_MODEM_SIM7600
lib_deps =
    knolleary/PubSubClient @ ^2.8
    vshymanskyy/TinyGSM @ ^0.12.0

[env:esp32-sim800]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200
build_flags = -D TINY_GSM_MODEM_SIM800
lib_deps =
    knolleary/PubSubClient @ ^2.8
    vshymanskyy/TinyGSM @ ^0.12.0
